name: regina_portfolio
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.2
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.0
  lottie: ^3.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/json/
    - .env
